batch_size: 400
epochs: 1000
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 1e-6
fp16_precision: False

model:
  out_dim: 512
  base_model: "resnet18"

dataset:
  s: 0.5
  input_shape: (32,32,3)
  num_workers: 3
  valid_size: 0.05

loss:
  temperature: 0.5
  use_cosine_similarity: True
